### PR TITLE
Perform applications validation on pull request

### PR DESCRIPTION
**Pull request by JanWittler**
Perform application validation on every pull request to avoid cases like in #101.
Like in the framework repository application validation, uses the branch matching the current branch name in the application's repository (if any), otherwise the master branch. Always uses the framework master branch to enforce merge order framework -> domains -> applications.

### CODE REVIEW

**Review by HeikoKlare — COMMENTED** [review]
It's obviously good to have this additional check against the applications. However, I am not sure whether we really need to checkout and build the framework. In case there are framework changes on an appropriate branch, the validation will be performed in the framework PR anyway. In case that we only perform domain changes that require adaptation of the applications, there is no need to rebuild the framework, as we can simply use the updatesite version. Removing the framework build would significantly improve the execution speed of the action. Or am I missing something?

**Comment by JanWittler** [comment]
I thought we could run into problems where the nightly build is behind the framework master branch but I just saw that the nightly build is also updated on push to master, if I understand the ci.yml correctly? Then building the framework should not be necessary.

**Comment by HeikoKlare** [comment]
Correct, the nightly updatesite should always contain the version built from master head. It is built after changes to the master branch and, as the name indicates, every night.
According to your intention, there may only be two reasons where this might make problems. First, the master branch was changed but the deployment has not been performed yet (which will be the case for the first ~10 minutes after a change to the master branch). Second, the master branch was changed and the deployment build has been run but failed, which should usually not be the case if the PR build has succeeded before.
However, especially in the latter case it would be beneficial to receive a notification about the missing framework deployment, as otherwise the validation may indicate that the build will succeed after merging the PR but actually it won't.

**Comment by JanWittler** [comment]
Thank you for the hint. I adjusted the action accordingly.

**Review by HeikoKlare — APPROVED** [review]
Thank you! Will be helpful to have this additional validation as well.

**Pull request merged**
